Problem: can't get reproducible dev. env.
Solution:

To get reproducible development enviornments, it's suggested we use
`direnv allow`, which uses `flake.nix`.

However, when we run `direnv allow`, we get:

```
λ direnv allow
direnv: loading ~/github/lurk-rs/.envrc
direnv: using flake
evaluating derivation 'git+file:///home/sweater/github/lurk-rs#devShells.x86_64-linux.default'direnv: ([/nix/store/3nkxf3pa2qg4884xahpm3q2hbpn30ipi-direnv-2.32.1/bin/direnv export bash]) is taking a while to execute. Use CTRL-C to give up.
error: hash mismatch in fixed-output derivation '/nix/store/7k41svra9sf9dxpil6857m55p29s4fnf-channel-rust-1.68.2.toml.drv':
         specified: sha256-S4dA7ne2IpFHG+EnjXfogmqwGyDFSRWFnJ8cy4KZr1k=
            got:    sha256-4vetmUhTUsew5FODnjlnQYInzyLNyDwocGa4IvMk3DM=
(use '--show-trace' to show detailed location information)
direnv: nix-direnv: renewed cache
direnv: export ~XDG_DATA_DIRS
```

To workaround this, we replaced the hash with the expected one.

However, supposedly the previous hash used to work before. Thus, we need to further investigate the reason for the hash divergence.